export type ControlCenterLocale = 'en' | 'ar';
const enStatuses: Record<string, string> = {
  lead: 'Lead',
  trial: 'Trial',
  active: 'Active',
  grace: 'Grace',
  restricted: 'Restricted',
  terminated: 'Terminated',
  archived: 'Archived',
  healthy: 'Healthy',
  attention: 'Needs attention',
  blocked: 'Blocked',
  clear: 'Clear',
  open: 'Open',
  escalated: 'Escalated',
};
const arStatuses: Record<string, string> = {
  lead: 'عميل محتمل',
  trial: 'تجريبي',
  active: 'نشط',
  grace: 'مهلة',
  restricted: 'مقيّد',
  terminated: 'منتهي',
  archived: 'مؤرشف',
  healthy: 'سليم',
  attention: 'يحتاج متابعة',
  blocked: 'متوقف',
  clear: 'لا توجد حالات',
  open: 'مفتوح',
  escalated: 'مصعّد',
};
export const controlCenterCopy = {
  en: {
    eyebrow: 'Client operations',
    title: 'ISP client lifecycle',
    description:
      'Find a client, inspect deployment and support context, then complete a guarded task.',
    search: 'Search legal or trading name',
    state: 'Lifecycle state',
    health: 'Deployment health',
    support: 'Support status',
    all: 'All',
    apply: 'Apply filters',
    reset: 'Reset',
    add: 'Add ISP client',
    table: 'Filtered ISP clients',
    client: 'Client',
    lifecycle: 'Lifecycle',
    package: 'Package',
    deployment: 'Deployment',
    tickets: 'Support',
    action: 'Task',
    open: 'Open workspace',
    loadingTitle: 'Loading client work queue',
    loadingBody: 'Checking the latest lifecycle, billing, deployment, and support summaries.',
    emptyTitle: 'No clients match these filters',
    emptyBody: 'Clear one or more filters or add a new ISP client.',
    errorTitle: 'The client work queue could not be loaded',
    errorBody: 'Retry the request. No client record was changed.',
    denialTitle: 'You do not have access to client records',
    denialBody:
      'Ask a platform administrator for the client view permission. This screen cannot request or elevate access.',
    successTitle: 'Client task saved',
    successBody: 'The guarded change and its audit record were accepted.',
    retry: 'Retry',
    clear: 'Clear filters',
    audit: 'View audit record',
    resultCount: (count: number) => `${count} clients`,
    statusLabels: enStatuses,
  },
  ar: {
    eyebrow: 'عمليات العملاء',
    title: 'دورة حياة عميل مزوّد الإنترنت',
    description: 'ابحث عن العميل وراجع حالة النشر والدعم ثم نفّذ مهمة محمية.',
    search: 'البحث بالاسم القانوني أو التجاري',
    state: 'حالة دورة الحياة',
    health: 'حالة النشر',
    support: 'حالة الدعم',
    all: 'الكل',
    apply: 'تطبيق المرشحات',
    reset: 'إعادة الضبط',
    add: 'إضافة عميل مزوّد',
    table: 'عملاء مزوّد الإنترنت المصنّفون',
    client: 'العميل',
    lifecycle: 'دورة الحياة',
    package: 'الباقة',
    deployment: 'النشر',
    tickets: 'الدعم',
    action: 'المهمة',
    open: 'فتح مساحة العمل',
    loadingTitle: 'جارٍ تحميل قائمة عمل العملاء',
    loadingBody: 'يتم التحقق من أحدث ملخصات دورة الحياة والفوترة والنشر والدعم.',
    emptyTitle: 'لا يوجد عملاء مطابقون',
    emptyBody: 'امسح بعض المرشحات أو أضف عميل مزوّد جديداً.',
    errorTitle: 'تعذّر تحميل قائمة عمل العملاء',
    errorBody: 'أعد المحاولة. لم يتم تغيير أي سجل عميل.',
    denialTitle: 'ليس لديك صلاحية لعرض سجلات العملاء',
    denialBody:
      'اطلب من مسؤول المنصة صلاحية عرض العملاء. لا يمكن لهذه الشاشة طلب الصلاحيات أو رفعها.',
    successTitle: 'تم حفظ مهمة العميل',
    successBody: 'تم قبول التغيير المحمي وسجل التدقيق الخاص به.',
    retry: 'إعادة المحاولة',
    clear: 'مسح المرشحات',
    audit: 'عرض سجل التدقيق',
    resultCount: (count: number) => `${count} عملاء`,
    statusLabels: arStatuses,
  },
} as const;
