export type Locale = 'en' | 'ar';

const copy = {
  en: {
    appName: 'Orvex ISP Collect',
    reference: 'Reference mode — no tenant backend connected',
    assignedRoute: 'Assigned route',
    customers: 'customers',
    offline: 'Offline',
    online: 'Online',
    queue: 'Sync queue',
    conflicts: 'conflicts',
    subscriber: 'Subscriber',
    outstanding: 'Outstanding',
    collect: 'Collect payment',
    amount: 'Amount in minor units',
    currency: 'Currency',
    method: 'Method',
    allocation: 'Invoice allocation',
    note: 'Note',
    proof: 'Proof reference',
    save: 'Save securely and queue',
    saveFailure: 'The payment could not be saved.',
    queued: 'Payment saved to the encrypted outbox',
    provisional: 'Provisional receipt',
    print: 'Print receipt',
    printerFailure: 'Printer unavailable. The payment remains saved and can be reprinted.',
    reconciliation: 'End-of-day reconciliation',
    expected: 'Expected',
    declared: 'Declared',
    difference: 'Difference',
    submit: 'Queue reconciliation',
    manager: 'Manager approval required for discrepancy',
    featureUnavailable: 'This feature is not enabled for this device.',
    revoked:
      'Device revoked. Sync, assignments, and new collections are locked. Contact an administrator for audited recovery.',
    expired: 'Offline assignment access expired. Reconnect and authenticate again.',
    loading: 'Loading protected assignments…',
    empty: 'No assigned subscribers are available.',
    retry: 'Retry sync',
    help: 'Help and device account',
    security:
      'Data is stored only in encrypted device storage. Server authorization remains final.',
  },
  ar: {
    appName: 'Orvex ISP Collect',
    reference: 'وضع مرجعي — لا يوجد اتصال بنظام المؤسسة',
    assignedRoute: 'المسار المكلّف',
    customers: 'مشتركين',
    offline: 'غير متصل',
    online: 'متصل',
    queue: 'قائمة المزامنة',
    conflicts: 'تعارضات',
    subscriber: 'المشترك',
    outstanding: 'المبلغ المستحق',
    collect: 'تحصيل دفعة',
    amount: 'المبلغ بالوحدة الصغرى',
    currency: 'العملة',
    method: 'طريقة الدفع',
    allocation: 'تخصيص الفاتورة',
    note: 'ملاحظة',
    proof: 'مرجع الإثبات',
    save: 'حفظ آمن وإضافة للمزامنة',
    saveFailure: 'تعذّر حفظ الدفعة.',
    queued: 'تم حفظ الدفعة في قائمة المزامنة المشفّرة',
    provisional: 'إيصال مبدئي',
    print: 'طباعة الإيصال',
    printerFailure: 'الطابعة غير متاحة. الدفعة محفوظة ويمكن إعادة طباعتها.',
    reconciliation: 'مطابقة نهاية اليوم',
    expected: 'المتوقع',
    declared: 'المصرّح',
    difference: 'الفرق',
    submit: 'إضافة المطابقة للمزامنة',
    manager: 'يلزم اعتماد المدير عند وجود فرق',
    featureUnavailable: 'هذه الميزة غير مفعّلة لهذا الجهاز.',
    revoked:
      'تم إلغاء الجهاز. المزامنة والتكليفات والتحصيل مقفلة. تواصل مع المسؤول للاسترداد الموثّق.',
    expired: 'انتهت صلاحية التكليفات المخزنة. اتصل وسجّل الدخول من جديد.',
    loading: 'جارٍ تحميل التكليفات المحمية…',
    empty: 'لا يوجد مشتركون مكلّفون حالياً.',
    retry: 'إعادة المزامنة',
    help: 'المساعدة وحساب الجهاز',
    security: 'تُحفظ البيانات فقط في تخزين الجهاز المشفّر. صلاحية الخادم هي المرجع النهائي.',
  },
} as const;

export function t(locale: Locale): (key: keyof (typeof copy)['en']) => string {
  return (key) => copy[locale][key];
}
