#!/bin/sh
# Orvex ISP production checkpoint deployment.
#
# Deploys exactly one reviewed, pushed commit to the `orvex-isp-prod` Compose project.
# Every step before "PHASE 5" is read-only or additive, so the currently running release
# keeps serving traffic until the checkpoint is proven deployable. In particular the
# migration checksum preflight runs against the live database *before* any container is
# recreated: a packaging defect then costs zero downtime instead of an outage.
#
# Scope discipline: this script only ever touches /opt/orvex-isp, the orvex-isp-prod
# Compose project, and /opt/orvex-backups. It never inspects or changes another workload.
#
# Usage (on the production host):
#   ORVEX_DEPLOY_ACK=production-checkpoint-authorized \
#     /opt/orvex-isp/deploy/production/deploy-checkpoint.sh <commit-sha>
#
set -eu

SOURCE_ROOT=/opt/orvex-isp
COMPOSE_FILE="$SOURCE_ROOT/deploy/production/docker-compose.yml"
ENV_FILE="$SOURCE_ROOT/.env"
COMPOSE_PROJECT=orvex-isp-prod
BACKUP_ROOT=/opt/orvex-backups
PUBLIC_BASE=https://isp.mosesgr.com
MIN_FREE_KB=5242880 # 5 GiB

TARGET_SHA="${1:-}"

compose() {
  docker compose --project-name "$COMPOSE_PROJECT" --env-file "$ENV_FILE" -f "$COMPOSE_FILE" "$@"
}

fail() {
  echo "DEPLOY ABORTED: $*" >&2
  exit 1
}

step() {
  echo ""
  echo "=== $* ==="
}

# ---------------------------------------------------------------------------
# PHASE 0 — authorization and argument validation
# ---------------------------------------------------------------------------
step "PHASE 0: authorization"
[ "${ORVEX_DEPLOY_ACK:-}" = "production-checkpoint-authorized" ] ||
  fail "set ORVEX_DEPLOY_ACK=production-checkpoint-authorized to confirm a production change"
[ -n "$TARGET_SHA" ] || fail "a target commit sha is required"
echo "$TARGET_SHA" | grep -Eq '^[0-9a-f]{40}$' ||
  fail "the target must be a full 40-character commit sha, not a branch name"
[ -d "$SOURCE_ROOT" ] || fail "$SOURCE_ROOT is missing"
[ -f "$ENV_FILE" ] || fail "$ENV_FILE is missing; it is never regenerated by this script"
[ -f "$COMPOSE_FILE" ] || fail "$COMPOSE_FILE is missing"
echo "Authorized. Target commit: $TARGET_SHA"

RELEASE_ID="$(date -u +%Y%m%dT%H%M%SZ)-$(echo "$TARGET_SHA" | cut -c1-7)"
BACKUP_DIR="$BACKUP_ROOT/$RELEASE_ID"

# ---------------------------------------------------------------------------
# PHASE 1 — read-only preflight against the release currently serving traffic
# ---------------------------------------------------------------------------
step "PHASE 1: read-only preflight"

FREE_KB="$(df -Pk "$SOURCE_ROOT" | awk 'NR==2 {print $4}')"
[ "$FREE_KB" -ge "$MIN_FREE_KB" ] ||
  fail "only ${FREE_KB}KB free on $SOURCE_ROOT; need at least ${MIN_FREE_KB}KB for backup and images"
echo "Free space: ${FREE_KB}KB"

READY_BEFORE="$(curl -fsS --max-time 20 "$PUBLIC_BASE/ready" || true)"
echo "Readiness before: ${READY_BEFORE:-<unreachable>}"
[ -n "$READY_BEFORE" ] ||
  fail "the current release is not ready; resolve the existing incident before deploying"

echo "Container state before:"
compose ps --format 'table {{.Service}}\t{{.State}}\t{{.Status}}'

compose config --quiet || fail "the Compose model is invalid"
echo "Compose model valid for project $COMPOSE_PROJECT"

# ---------------------------------------------------------------------------
# PHASE 2 — fetch the exact commit without disturbing the running release
# ---------------------------------------------------------------------------
step "PHASE 2: fetch target commit"
cd "$SOURCE_ROOT"
git fetch --quiet origin
git cat-file -e "${TARGET_SHA}^{commit}" 2>/dev/null ||
  fail "commit $TARGET_SHA is not present on origin"
CURRENT_SHA="$(git rev-parse HEAD)"
echo "Deployed commit: $CURRENT_SHA"
echo "Target commit:   $TARGET_SHA"
[ "$CURRENT_SHA" != "$TARGET_SHA" ] || fail "target equals the deployed commit; nothing to promote"

# ---------------------------------------------------------------------------
# PHASE 3 — backup source, control database, tenant database
# ---------------------------------------------------------------------------
step "PHASE 3: backup to $BACKUP_DIR"
if [ -e "$BACKUP_DIR" ]; then
  fail "$BACKUP_DIR already exists; refusing to overwrite a backup"
fi
mkdir -p "$BACKUP_DIR"

git -C "$SOURCE_ROOT" archive --format=tar --prefix=orvex-isp/ "$CURRENT_SHA" \
  >"$BACKUP_DIR/source-$CURRENT_SHA.tar"
cp "$ENV_FILE" "$BACKUP_DIR/env.backup"
chmod 600 "$BACKUP_DIR/env.backup"

# Historical migration bytes are backed up separately: restoring them is the documented
# recovery path when a packaging defect changes an applied migration's checksum.
tar -cf "$BACKUP_DIR/migrations-$CURRENT_SHA.tar" -C "$SOURCE_ROOT" packages/database/migrations

compose exec -T postgres pg_dump -U orvex_bootstrap -Fc orvex_control \
  >"$BACKUP_DIR/orvex_control.dump"
compose exec -T postgres pg_dump -U orvex_bootstrap -Fc orvex_tenant \
  >"$BACKUP_DIR/orvex_tenant.dump"

compose exec -T postgres psql -U orvex_bootstrap -d orvex_tenant -At -F ' ' -c \
  'SELECT name, checksum FROM public._orvex_migrations ORDER BY name' \
  >"$BACKUP_DIR/tenant-migration-ledger.txt" 2>/dev/null ||
  echo "(tenant ledger capture skipped)" >"$BACKUP_DIR/tenant-migration-ledger.txt"
compose exec -T postgres psql -U orvex_bootstrap -d orvex_control -At -F ' ' -c \
  'SELECT name, checksum FROM public._orvex_migrations ORDER BY name' \
  >"$BACKUP_DIR/control-migration-ledger.txt" 2>/dev/null ||
  echo "(control ledger capture skipped)" >"$BACKUP_DIR/control-migration-ledger.txt"

( cd "$BACKUP_DIR" && sha256sum ./* >SHA256SUMS && sha256sum -c SHA256SUMS ) ||
  fail "backup checksum verification failed"
echo "Backup verified: $BACKUP_DIR"

# ---------------------------------------------------------------------------
# PHASE 4 — check out the target, verify packaging, preflight migrations
#           (services are still running the previous release throughout)
# ---------------------------------------------------------------------------
step "PHASE 4: checkout and preflight"
git -C "$SOURCE_ROOT" checkout --quiet --detach "$TARGET_SHA"
echo "Checked out $(git rev-parse HEAD)"

# The .gitattributes contract guarantees LF; verify it survived this checkout before trusting it.
for script in $(git -C "$SOURCE_ROOT" ls-files '*.sh'); do
  if grep -q "$(printf '\r')" "$SOURCE_ROOT/$script"; then
    fail "$script contains CRLF; migration checksums and Alpine execution are unsafe"
  fi
  [ -x "$SOURCE_ROOT/$script" ] || fail "$script is not executable in the checkout"
done
if grep -rlq "$(printf '\r')" "$SOURCE_ROOT/packages/database/migrations"; then
  fail "a migration file contains CRLF; its checksum will not match the applied ledger"
fi
echo "Packaging verified: LF-only migrations, executable shell scripts"

# Build images now. Building does not touch the running containers.
compose build migrate api finance-audit-relay network-worker web ||
  fail "image build failed; the previous release is still running and untouched"

# The decisive gate: compare packaged migration bytes against the live applied ledger.
compose run --rm --no-deps --entrypoint node migrate \
  packages/database/scripts/preflight-migrations.mjs ||
  fail "migration preflight failed. Do NOT recreate services. Restore historical migration bytes from $BACKUP_DIR/migrations-$CURRENT_SHA.tar and fix the release artifact. Never edit _orvex_migrations."

# ---------------------------------------------------------------------------
# PHASE 5 — apply migrations and provisioning (first mutating phase)
# ---------------------------------------------------------------------------
step "PHASE 5: migrate and provision"
compose up --no-deps --exit-code-from migrate migrate ||
  fail "migration failed; inspect 'compose logs migrate' and do not rerun blindly"
compose up --no-deps --exit-code-from provision-context provision-context ||
  fail "context provisioning failed; inspect 'compose logs provision-context'"
echo "Migrations and provisioning completed with exit code 0"

# ---------------------------------------------------------------------------
# PHASE 6 — recreate services: data plane and workers first, web last
# ---------------------------------------------------------------------------
step "PHASE 6: recreate services"
compose up -d --no-deps finance-audit-relay network-worker
compose up -d --no-deps api

waited=0
until curl -fsS --max-time 10 "$PUBLIC_BASE/ready" >/dev/null 2>&1; do
  waited=$((waited + 5))
  [ "$waited" -le 180 ] || fail "the API did not become ready within 180s"
  sleep 5
done
echo "API ready after ${waited}s"

compose up -d --no-deps web

# ---------------------------------------------------------------------------
# PHASE 7 — verification
# ---------------------------------------------------------------------------
step "PHASE 7: verification"
for path in "/ready" "/" "/control/"; do
  code="$(curl -fsS -o /dev/null -w '%{http_code}' --max-time 25 "$PUBLIC_BASE$path" || echo 000)"
  echo "  $path -> HTTP $code"
  [ "$code" = "200" ] || fail "$path returned HTTP $code"
done
echo "Readiness body: $(curl -fsS --max-time 20 "$PUBLIC_BASE/ready")"

# Read-only invariants. Journal balance is asserted per entry per currency, because a
# balanced total across USD and LBP would itself be a currency-mixing defect.
UNBALANCED="$(compose exec -T postgres psql -U orvex_bootstrap -d orvex_tenant -Atc "
  SELECT count(*) FROM (
    SELECT journal_entry_id, currency
    FROM operations_journal_lines
    GROUP BY journal_entry_id, currency
    HAVING sum(debit_minor) <> sum(credit_minor)
  ) AS unbalanced")"
INVALID_INDEXES="$(compose exec -T postgres psql -U orvex_bootstrap -d orvex_tenant -Atc "
  SELECT count(*) FROM pg_index WHERE NOT indisvalid OR NOT indisready")"
echo "  unbalanced journal entries: $UNBALANCED"
echo "  invalid database indexes:   $INVALID_INDEXES"
[ "$UNBALANCED" = "0" ] || fail "unbalanced journal entries detected after deployment"
[ "$INVALID_INDEXES" = "0" ] || fail "invalid database indexes detected after deployment"

echo "Container state after:"
compose ps --format 'table {{.Service}}\t{{.State}}\t{{.Status}}'

echo "Recent errors (api, workers, web):"
compose logs --since 5m --no-color api finance-audit-relay network-worker web 2>&1 |
  grep -iE '\b(error|fatal|panic|unhandled)\b' | tail -20 || echo "  none"

# ---------------------------------------------------------------------------
# PHASE 8 — report
# ---------------------------------------------------------------------------
step "PHASE 8: checkpoint report"
cat <<REPORT
Release id:        $RELEASE_ID
Promoted commit:   $TARGET_SHA
Rollback boundary: $CURRENT_SHA (source + databases in $BACKUP_DIR)
Backup:            $BACKUP_DIR (verified with SHA256SUMS)
Migrations:        applied through $(compose exec -T postgres psql -U orvex_bootstrap -d orvex_tenant -Atc 'SELECT max(name) FROM public._orvex_migrations')
Endpoints:         / 200, /control/ 200, /ready 200
Invariants:        unbalanced journals $UNBALANCED, invalid indexes $INVALID_INDEXES

The pre-deployment backup is retained. Prune only build caches, never $BACKUP_ROOT.
REPORT

# Build cache only. Never prune volumes, never touch other workloads' images.
docker builder prune --force --filter until=168h >/dev/null 2>&1 || true
echo "Deployment complete."
