#!/bin/sh
# Orvex ISP production checkpoint deployment.
#
# Deploys exactly one reviewed, pushed commit to the `orvex-isp-prod` Compose project from an
# immutable artifact built by `scripts/release/build-release-artifact.mjs`. Everything before
# "PHASE 6" is read-only or staged, so the running release keeps serving traffic until the
# checkpoint is proven deployable.
#
# Two production facts shape this script:
#
#   1. /opt/orvex-isp is a plain extracted tree, not a git checkout. The artifact is uploaded
#      and unpacked; nothing here talks to a git remote.
#   2. Twelve tenant migrations (202609021800-202609021811) were applied on 2026-09-04 from a
#      CRLF checkout, so `_orvex_migrations` records CRLF checksums for them while the
#      repository is now LF. Applied migrations are immutable *including the bytes that were
#      applied*, so PHASE 4 preserves every already-applied migration file exactly as the
#      server holds it and unpacks only genuinely new forward migrations. Overwriting them
#      with LF bytes would abort the migrator after services were already stopped, and
#      editing the stored checksums to match is forbidden.
#
# Scope discipline: only /opt/orvex-isp, the orvex-isp-prod Compose project, /opt/orvex-backups
# and /opt/orvex-releases are touched. No other workload on this host is inspected or changed.
#
# Usage (on the production host):
#   ORVEX_DEPLOY_ACK=production-checkpoint-authorized \
#     /opt/orvex-isp/deploy/production/deploy-checkpoint.sh <commit-sha> <artifact.tar>
#
set -eu

SOURCE_ROOT=/opt/orvex-isp
COMPOSE_FILE="$SOURCE_ROOT/deploy/production/docker-compose.yml"
ENV_FILE="$SOURCE_ROOT/.env"
COMPOSE_PROJECT=orvex-isp-prod
BACKUP_ROOT=/opt/orvex-backups
RELEASE_ROOT=/opt/orvex-releases
PUBLIC_BASE=https://isp.mosesgr.com
MIN_FREE_KB=5242880 # 5 GiB

TARGET_SHA="${1:-}"
ARTIFACT="${2:-}"

compose() {
  docker compose --project-name "$COMPOSE_PROJECT" --env-file "$ENV_FILE" -f "$COMPOSE_FILE" "$@"
}

fail() {
  echo "DEPLOY ABORTED: $*" >&2
  exit 1
}

step() {
  echo ""
  echo "=== $* ==="
}

# ---------------------------------------------------------------------------
# PHASE 0 — authorization and argument validation
# ---------------------------------------------------------------------------
step "PHASE 0: authorization"
[ "${ORVEX_DEPLOY_ACK:-}" = "production-checkpoint-authorized" ] ||
  fail "set ORVEX_DEPLOY_ACK=production-checkpoint-authorized to confirm a production change"
[ -n "$TARGET_SHA" ] || fail "a target commit sha is required"
echo "$TARGET_SHA" | grep -Eq '^[0-9a-f]{40}$' ||
  fail "the target must be a full 40-character commit sha, not a branch name"
[ -n "$ARTIFACT" ] && [ -f "$ARTIFACT" ] || fail "an uploaded release artifact tar is required"
[ -d "$SOURCE_ROOT" ] || fail "$SOURCE_ROOT is missing"
[ -f "$ENV_FILE" ] || fail "$ENV_FILE is missing; it is never regenerated by this script"
[ -f "$COMPOSE_FILE" ] || fail "$COMPOSE_FILE is missing"
echo "Authorized. Target commit: $TARGET_SHA"

RELEASE_ID="$(date -u +%Y%m%dT%H%M%SZ)-$(echo "$TARGET_SHA" | cut -c1-7)"
BACKUP_DIR="$BACKUP_ROOT/$RELEASE_ID"
STAGE_DIR="$RELEASE_ROOT/$RELEASE_ID"

# ---------------------------------------------------------------------------
# PHASE 1 — read-only preflight against the release currently serving traffic
# ---------------------------------------------------------------------------
step "PHASE 1: read-only preflight"

FREE_KB="$(df -Pk "$SOURCE_ROOT" | awk 'NR==2 {print $4}')"
[ "$FREE_KB" -ge "$MIN_FREE_KB" ] ||
  fail "only ${FREE_KB}KB free on $SOURCE_ROOT; need at least ${MIN_FREE_KB}KB"
echo "Free space: ${FREE_KB}KB"

READY_BEFORE="$(curl -fsS --max-time 20 "$PUBLIC_BASE/ready" || true)"
echo "Readiness before: ${READY_BEFORE:-<unreachable>}"
[ -n "$READY_BEFORE" ] ||
  fail "the current release is not ready; resolve the existing incident before deploying"

echo "Container state before:"
compose ps --format 'table {{.Service}}\t{{.State}}\t{{.Status}}'
compose config --quiet || fail "the Compose model is invalid"
echo "Compose model valid for project $COMPOSE_PROJECT"

# ---------------------------------------------------------------------------
# PHASE 2 — stage the artifact without touching the live tree
# ---------------------------------------------------------------------------
step "PHASE 2: stage artifact"
if [ -e "$STAGE_DIR" ]; then fail "$STAGE_DIR already exists"; fi
mkdir -p "$STAGE_DIR"
tar -xf "$ARTIFACT" -C "$STAGE_DIR" --strip-components=1
[ -f "$STAGE_DIR/packages/database/scripts/migrate.mjs" ] ||
  fail "the artifact does not contain the expected source tree"
echo "Staged $(find "$STAGE_DIR" -type f | wc -l) files in $STAGE_DIR"

# The artifact must carry LF-only migrations and executable shell scripts.
for script in $(find "$STAGE_DIR" -name '*.sh' -type f); do
  [ -x "$script" ] || fail "${script#"$STAGE_DIR"/} is not executable in the artifact"
  ! grep -q "$(printf '\r')" "$script" || fail "${script#"$STAGE_DIR"/} contains CRLF"
done
echo "Artifact verified: executable shell scripts, no CRLF in shell scripts"

# ---------------------------------------------------------------------------
# PHASE 3 — backup source, .env, migration bytes, both databases and ledgers
# ---------------------------------------------------------------------------
step "PHASE 3: backup to $BACKUP_DIR"
if [ -e "$BACKUP_DIR" ]; then fail "$BACKUP_DIR already exists; refusing to overwrite a backup"; fi
mkdir -p "$BACKUP_DIR"

tar -cf "$BACKUP_DIR/source.tar" -C "$(dirname "$SOURCE_ROOT")" "$(basename "$SOURCE_ROOT")"
cp "$ENV_FILE" "$BACKUP_DIR/env.backup"
chmod 600 "$BACKUP_DIR/env.backup"

# Historical migration bytes are backed up on their own: restoring them is the documented
# recovery path if an applied migration's checksum ever stops matching.
tar -cf "$BACKUP_DIR/migrations.tar" -C "$SOURCE_ROOT" packages/database/migrations

for db in orvex_control orvex_tenant; do
  compose exec -T postgres pg_dump -U orvex_bootstrap -Fc "$db" >"$BACKUP_DIR/$db.dump"
  compose exec -T postgres psql -U orvex_bootstrap -d "$db" -At -F '|' \
    -c 'SELECT name, checksum FROM public._orvex_migrations ORDER BY name' \
    >"$BACKUP_DIR/$db-migration-ledger.txt"
done

(cd "$BACKUP_DIR" && sha256sum ./* >SHA256SUMS && sha256sum -c SHA256SUMS >/dev/null) ||
  fail "backup checksum verification failed"
echo "Backup verified: $BACKUP_DIR"

# ---------------------------------------------------------------------------
# PHASE 4 — preserve already-applied migration bytes in the staged tree
# ---------------------------------------------------------------------------
step "PHASE 4: reconcile migrations"
APPLIED_LIST="$BACKUP_DIR/applied-migrations.txt"
compose exec -T postgres psql -U orvex_bootstrap -d orvex_tenant -At \
  -c 'SELECT name FROM public._orvex_migrations' | tr -d '\r' >"$APPLIED_LIST"
compose exec -T postgres psql -U orvex_bootstrap -d orvex_control -At \
  -c 'SELECT name FROM public._orvex_migrations' | tr -d '\r' >>"$APPLIED_LIST"
sort -u "$APPLIED_LIST" -o "$APPLIED_LIST"

preserved=0
while IFS= read -r name; do
  [ -n "$name" ] || continue
  live="$SOURCE_ROOT/packages/database/migrations/$name"
  staged="$STAGE_DIR/packages/database/migrations/$name"
  [ -f "$live" ] || fail "applied migration $name is missing from the live tree"
  if ! cmp -s "$live" "$staged" 2>/dev/null; then
    # Applied bytes win. This is what keeps the recorded checksum valid.
    cp -p "$live" "$staged"
    preserved=$((preserved + 1))
  fi
done <"$APPLIED_LIST"
echo "Preserved $preserved already-applied migration file(s) byte-for-byte from the live tree"

new_migrations=0
for staged in "$STAGE_DIR"/packages/database/migrations/*.sql; do
  name="$(basename "$staged")"
  grep -qxF "$name" "$APPLIED_LIST" || {
    echo "  forward migration: $name"
    new_migrations=$((new_migrations + 1))
  }
done
echo "Forward migrations to promote: $new_migrations"

# ---------------------------------------------------------------------------
# PHASE 5 — migration checksum preflight against the live database
#           (services are still running the previous release)
# ---------------------------------------------------------------------------
step "PHASE 5: migration checksum preflight"
cp "$ENV_FILE" "$STAGE_DIR/.env"
chmod 600 "$STAGE_DIR/.env"

(cd "$STAGE_DIR" && docker compose --project-name "$COMPOSE_PROJECT" --env-file .env \
  -f deploy/production/docker-compose.yml build migrate) ||
  fail "migrate image build failed; the previous release is still running and untouched"

(cd "$STAGE_DIR" && docker compose --project-name "$COMPOSE_PROJECT" --env-file .env \
  -f deploy/production/docker-compose.yml run --rm --no-deps --entrypoint node migrate \
  packages/database/scripts/preflight-migrations.mjs) ||
  fail "migration preflight failed. Do NOT recreate services. The staged tree is untouched at $STAGE_DIR and the live release is still serving. Fix the artifact; never edit _orvex_migrations."

# ---------------------------------------------------------------------------
# PHASE 6 — publish the staged tree over the live tree (first mutating step)
# ---------------------------------------------------------------------------
step "PHASE 6: publish source"
# .env and the applied migrations are already correct in the staged tree, so a plain copy
# is safe. Files removed upstream are not deleted here; that is a deliberate conservative
# choice on a host that also stores runtime output under this root.
(cd "$STAGE_DIR" && tar -cf - .) | (cd "$SOURCE_ROOT" && tar -xf -)
echo "Published $TARGET_SHA into $SOURCE_ROOT"

# ---------------------------------------------------------------------------
# PHASE 7 — build, migrate, provision
# ---------------------------------------------------------------------------
step "PHASE 7: build, migrate, provision"
compose build api finance-audit-relay network-worker web ||
  fail "image build failed after publish; roll back with $BACKUP_DIR/source.tar"
compose up --no-deps --exit-code-from migrate migrate ||
  fail "migration failed; inspect 'compose logs migrate' and do not rerun blindly"
compose up --no-deps --exit-code-from provision-context provision-context ||
  fail "context provisioning failed; inspect 'compose logs provision-context'"
echo "Migration and provisioning completed with exit code 0"

# ---------------------------------------------------------------------------
# PHASE 8 — recreate services: workers and API first, web last
# ---------------------------------------------------------------------------
step "PHASE 8: recreate services"
compose up -d --no-deps finance-audit-relay network-worker
compose up -d --no-deps api

waited=0
until curl -fsS --max-time 10 "$PUBLIC_BASE/ready" >/dev/null 2>&1; do
  waited=$((waited + 5))
  [ "$waited" -le 180 ] || fail "the API did not become ready within 180s"
  sleep 5
done
echo "API ready after ${waited}s"

compose up -d --no-deps web

# ---------------------------------------------------------------------------
# PHASE 9 — verification
# ---------------------------------------------------------------------------
step "PHASE 9: verification"
# The reverse proxy needs a moment to re-register the just-recreated web container, so a 502
# immediately after PHASE 8 is expected and transient. Poll each endpoint until it settles
# rather than aborting a deployment that actually succeeded.
#
# `-f` is deliberately omitted: with it curl exits non-zero on an error status and the
# fallback would be concatenated onto the code it already printed, yielding "502000".
check_endpoint() {
  endpoint="$1"
  elapsed=0
  while :; do
    code="$(curl -sS -o /dev/null -w '%{http_code}' --max-time 25 "$PUBLIC_BASE$endpoint" 2>/dev/null || true)"
    [ -n "$code" ] || code=000
    if [ "$code" = "200" ]; then
      echo "  $endpoint -> HTTP 200 (after ${elapsed}s)"
      return 0
    fi
    elapsed=$((elapsed + 5))
    [ "$elapsed" -le 120 ] || fail "$endpoint returned HTTP $code for ${elapsed}s after recreation"
    sleep 5
  done
}
for path in "/ready" "/" "/control/"; do check_endpoint "$path"; done
echo "Readiness body: $(curl -fsS --max-time 20 "$PUBLIC_BASE/ready")"

# Journal balance is asserted per entry per currency: a total that balances only after
# adding USD to LBP would itself be a currency-mixing defect.
UNBALANCED="$(compose exec -T postgres psql -U orvex_bootstrap -d orvex_tenant -Atc "
  SELECT count(*) FROM (
    SELECT journal_entry_id, currency
    FROM operations_journal_lines
    GROUP BY journal_entry_id, currency
    HAVING sum(debit_minor) <> sum(credit_minor)
  ) AS unbalanced" | tr -d '\r')"
INVALID_INDEXES="$(compose exec -T postgres psql -U orvex_bootstrap -d orvex_tenant -Atc "
  SELECT count(*) FROM pg_index WHERE NOT indisvalid OR NOT indisready" | tr -d '\r')"
echo "  unbalanced journal entries: $UNBALANCED"
echo "  invalid database indexes:   $INVALID_INDEXES"
[ "$UNBALANCED" = "0" ] || fail "unbalanced journal entries detected after deployment"
[ "$INVALID_INDEXES" = "0" ] || fail "invalid database indexes detected after deployment"

echo "Container state after:"
compose ps --format 'table {{.Service}}\t{{.State}}\t{{.Status}}'

echo "Recent errors (api, workers, web):"
compose logs --since 5m --no-color api finance-audit-relay network-worker web 2>&1 |
  grep -iE '\b(error|fatal|panic|unhandled)\b' | tail -20 || echo "  none"

# ---------------------------------------------------------------------------
# PHASE 10 — report
# ---------------------------------------------------------------------------
step "PHASE 10: checkpoint report"
APPLIED_MAX="$(compose exec -T postgres psql -U orvex_bootstrap -d orvex_tenant -Atc \
  'SELECT max(name) FROM public._orvex_migrations' | tr -d '\r')"
cat <<REPORT
Release id:          $RELEASE_ID
Promoted commit:     $TARGET_SHA
Backup:              $BACKUP_DIR (verified with SHA256SUMS)
Rollback boundary:   $BACKUP_DIR/source.tar plus orvex_control.dump and orvex_tenant.dump
Migrations promoted: $new_migrations (latest applied: $APPLIED_MAX)
Preserved applied:   $preserved file(s) kept at their applied bytes
Endpoints:           / 200, /control/ 200, /ready 200
Invariants:          unbalanced journals $UNBALANCED, invalid indexes $INVALID_INDEXES

The pre-deployment backup is retained. Prune only build caches, never $BACKUP_ROOT.
REPORT

docker builder prune --force --filter until=168h >/dev/null 2>&1 || true
echo "Deployment complete."
